App\Domain\User\ValueObject\Auth\Credentials:
  type: embeddable
  indexes:
      name_index:
        columns: [ email ]
  fields:
    email:
      type: string
      unique: true
    password:
      type: string