old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            keepalive: false

    producers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: topic }


    multiple_consumers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: topic }
            queues:
                projections_mysql:
                    name: projections_mysql
                    routing_keys:
                        - 'App.Domain.#'
                    callback: App\Infrastructure\Share\Event\Consumer\EventQueueConsumer