services:
    _defaults:
        public: true

    App\Tests\Infrastructure\Share\Event\InMemoryAsyncEventBusProducer:
        arguments:
          $asyncEventBus: '@tactician.commandbus.asyncEvent'

    App\Tests\Infrastructure\Share\Bus\EventCollectorMiddleware: ~

    old_sound_rabbit_mq.events_producer:
      alias: 'App\Tests\Infrastructure\Share\Event\InMemoryAsyncEventBusProducer'
      