services:
    _defaults:
        public: true

    App\Tests\Infrastructure\Share\Event\EventCollectorListener:
      public: true
      tags:
          - { name: broadway.domain.event_listener }

    App\Tests\Infrastructure\Share\Event\Publisher\InMemoryProducer: ~
    
    old_sound_rabbit_mq.events_producer:
      alias: 'App\Tests\Infrastructure\Share\Event\Publisher\InMemoryProducer'
